name: "OpenHAB"
description: "OpenHAB empowering the smart home"
version: "4.1.1"
slug: "openhab"
init: false
usb: true
uart: true
udev: true
arch:
  - amd64
map:
  - addon_config:rw
  - backup:rw
host_network: true
# Default options when used as an HA add-on
options:
  http_port: 8080
  https_port: 8443
  openhab_version: 4.1.1
# Schema for the options above
schema:
  http_port: int
  https_port: int
  openhab_version: str
